apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deployment-arnab
  namespace: demo
spec:
  selector:
    matchLabels:
      app: deployment-arnab
  template:
    metadata:
      labels:
        app: deployment-arnab
    spec:
      containers:
        - name: deployment-arnab
          image: arnabmj/scrum-dhaka:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000